### ISSUE TITLE
How to manage \n and \r line breaks within handlebars template?

### ISSUE THREAD

**Issue by JG-devo** [formspark/documentation#109]
I'm working with a form that has a message field:

`"message": "Testing the form, and how it looks\r\n\r\nHow to deal with paragraphs?",`

Normally with handlebars, you'd be able to register a new helper in JS to manage this, but it doesn't work on the template:

`Handlebars.registerHelper('paragraphs', function(message) {
  if (!message) return '';
  return message.split("\r\n").join("<br>");
});`

It would be amazing if you could include a function like this from your end, but if it's not possible - it would be good to have some documentation on handling this without JS in the template.

**Comment by botre** [comment]
Thank you for your suggestion, we may add this in a future release.

**Comment by TomDeSmet** [comment]
Is there a solution to handle new lines? I tried sending `\n` and `<br>` in my data object, but it's all converted to plain text in the backend and in the notification e-mails.

**Comment by billyberg** [comment]
Has anybody found a solution for this?
