### ISSUE TITLE
Line break

### ISSUE THREAD

**Issue by billyberg** [formspark/documentation#126]
I have an issue with line breaks.

I have a form set up with Webflow. When I receive the notification in my mail I get "\r\n" instead of the visitors line break. If I use a custom template the "\r\n" gets removed but it only replaces with a blank space and not a line break. 

How do I fix this?

**Comment by botre** [comment]
Hello,

Currently, line breaks and similar characters are not supported in the default email template, and we don't plan to add this feature soon. Blindly replacing \r and \n with new lines can cause issues, such as breaking URLs.

However, I have just added a new Handlebars helper to selectively format new lines in custom templates: https://documentation.formspark.io/dashboard/email-notification-settings.html#formatnewlines

Best regards,

**Comment by billyberg** [comment]
Thanks but I found a solution:
`<p style="white-space: pre-wrap;"><strong>{{@key}}</strong><br/>{{this}}</p>`

PS: The template builder just stoped working. It just opens a blank page..

**Comment by botre** [comment]
Hello, 

Happy to hear you managed to find a solution,

Thanks for the heads up, the page requires a hard-refresh to load the latest version, sorry about that!

**Comment by billyberg** [comment]
Ah, thanks. It works now 👍
