### ISSUE TITLE
Multiple entries

### ISSUE THREAD

**Issue by billyberg** [formspark/documentation#127]
Sometimes I get multiple entries from a forum made in Webflow. One time I even got 6 copies. Is this a bug or what?

The form you can find here: https://www.bizapartmenthotel.se/en/kontakt

**Comment by botre** [comment]
Hello,

Please check the following guide on how to disable the submit button while a form is submitting in Webflow:

https://technotrampoline.com/articles/how-to-disable-the-submit-button-while-a-form-is-submitting-in-webflow/

**Comment by billyberg** [comment]
Ah, you think that it could be this? I'll try it and get back to you if it doesn't work. Thanks!
