### ISSUE TITLE
Missing inputs

### ISSUE THREAD

**Issue by billyberg** [formspark/documentation#128]
I have a form on Webflow and the form wrapper ends with an embedded code with this code (see below). Sometimes the form does not send these inputs. Do I need to do anything else to ensure that these inputs are getting sent?

`<input type="hidden" name="_email.from" value="bizapartmenthotel.se" />
<input type="hidden" id="hotel" name="hotel" value="Gärdet">
<input type="hidden" name="_email.subject" value="Långtidsboende - Gärdet" />`

Here is the site: https://www.bizapartmenthotel.se/en/langtidsboende

**Comment by botre** [comment]
Did you manage to find your issue?

If not, feel free to reach out to support@formspark.io
