### ISSUE TITLE
Please demonstrate the use of an handlebar template by an example

### ISSUE THREAD

**Issue by gernotstarke** [formspark/documentation#88]
I currently have no idea WHERE to write the template code... into the forms' code? A distinct file? 

thanx for explaining :-)

**Comment by botre** [comment]
On your form's _Settings_ page there is a _Email notification template_ section where you can click _Create custom template (advanced)_.

**Comment by gernotstarke** [comment]
ok - thanx so much. Fixing issues in less than 30min counts as world-class support... awesome!
