### ISSUE TITLE
hCaptcha AJAX example is missing

### ISSUE THREAD

**Issue by aalaap** [formspark/documentation#89]
The documentation has examples for plain AJAX submissions, using reCAPTCHA as well as botpoison, but not hCaptcha. Botpoison needs `_botpoison`, reCAPTCHA needs `g-recaptcha-response`. What does hCaptcha need? I tried passing along `token` and `ekey` as returned by the hCaptcha React component, but that didn't work, so some documentation around this would be helpful.

**Comment by botre** [comment]
Hello,

Thanks for reaching out.

I apologize for the lack of documentation around these fields.

The name of the property is `h-captcha-response`.

I will be adding dedicated AJAX sections to improve clarity, thanks for your feedback 🤘

![Untitled](https://user-images.githubusercontent.com/10811687/132124714-ea54b76f-c9f9-4422-8ab5-c40131c99ed0.png)

Have a nice Sunday!

**Comment by aalaap** [comment]
@botre It works! Thank you so much!

Enjoy your Sunday!
