### ISSUE TITLE
integromat>> Make?

### ISSUE THREAD

**Issue by brwaddell** [formspark/documentation#99]
Hi, I see you've setup integromat (thanks that's amazing) but I can't find you in there now that they have rebranded to "make" ??

**Comment by botre** [comment]
Hello,

Thank you for reaching out.

Integromat and Make are two separate products.
Our Integromat integration is not compatible with Make.
A Make integration is in the works, however!

Keep an eye on our Twitter: https://twitter.com/formsparkapp

Cheers

**Comment by botre** [comment]
We now have an official Make integration: https://documentation.formspark.io/integration/make.html 🎉
